[parameters]
photon_threshold = 20.0
photon_low = 10.0
electron_threshold = 10.0
electron_low = 5.0
muon_threshold = 100.0
muon_low = 5.0
pion_threshold = 130.0
pion_low = 5.0
proton_threshold = 25.0
proton_low = 5.0

[general]
output = "/exp/sbnd/data/users/mdonnach/medulla_produce/single_photon_v2/selection/single_shower_v2_rewighted_1e20"
primfn = "default_primary_classification"
pidfn = "default_pid"
fsthresh = [
    "@photon_threshold",
    "@electron_threshold",
    "@muon_threshold",
    "@pion_threshold",
    "@proton_threshold",
]

# SBND sample
[[sample]]
name = "simulation"
#path = "/pnfs/sbnd/persistent/users/mueller/MCP2025B/simulation/mc5e18/input*-reweighted.flat.caf.root"
#path = "/pnfs/sbnd/persistent/users/mueller/MCP2025B/simulation/mc5e18/input*.flat.root"
#path = "/pnfs/sbnd/persistent/users/mueller/MCP2025B/simulation/mc1e20/input*.flat.root"
path = "/pnfs/sbnd/persistent/users/mueller/MCP2025B/simulation/mc1e20/input*-reweighted.flat.caf.root"
#path = "/pnfs/sbnd/scratch/users/mueller/MCP2025B/gen1_updated_training/03162026/input*.flat.root"
ismc = true
disable = false # Optional: default = falses


[[tree]]  #True single photon selection
name = "photon_true_neutrino"
sim_only = false
mode = "true"
cut = [
    { name = "single_photon_deposited_cut",             type = "true",  parameters = [ "@photon_threshold"  ] },
    { name = "no_electrons_inclusive",                  type = "true",  parameters = [ "@electron_threshold" ]},
    { name = "no_charged_pions_inclusive",              type = "true",  parameters = [ "@pion_threshold" ]},
    { name = "no_muon_inclusive",                       type = "true",  parameters = [ "@muon_threshold" ]},
    { name = "contained_fip_cut_depot",                 type = "true"},
    { name = "neutrino",                                type = "true"}
]
branch = [
    { name = "ke",                  type = "both_particle",     selector = "leading_depot_shower" },
    { name = "ke",                  type = "both_particle",     selector = "sub_leading_depot_shower" },
    { name = "total_depositions",   type = "both_particle",     selector = "leading_depot_shower"},
    { name = "total_depositions",   type = "both_particle",     selector = "sub_leading_depot_shower"},

    { name = "photon_multiplicity_inclusive",       type = "both", parameters = [ "@photon_threshold" ]},
    { name = "photon_depot_multiplicity_inclusive", type = "true", parameters = [ "@photon_threshold" ]},
    { name = "electron_multiplicity_inclusive",     type = "both", parameters = ["@electron_threshold"]},
    { name = "pion_multiplicity_inclusive",         type = "both", parameters = [ "@pion_threshold" ]},
    { name = "proton_multiplicity_inclusive",       type = "both", parameters = [ "@proton_threshold" ]},
    { name = "muon_multiplicity_inclusive",         type = "both", parameters = ["@muon_threshold"]},
    { name = "category",                            type = "true"},

    { name = "pid",                 type = "both_particle", selector="leading_depot_shower"},
    { name = "pid",                 type = "both_particle", selector="sub_leading_depot_shower"},
    { name = "shower_opening_angle",type = "both"},
    { name = "vertex_x",            type = "both"},    
    { name = "vertex_y",            type = "both"},
    { name = "vertex_z",            type = "both"},
    { name = "photon_softmax",      type = "reco_particle", selector = "leading_depot_shower"},
    { name = "photon_softmax",      type = "reco_particle", selector = "sub_leading_depot_shower"},
    { name = "electron_softmax",    type = "reco_particle", selector = "leading_depot_shower"},
    { name = "electron_softmax",    type = "reco_particle", selector = "sub_leading_depot_shower"},
    { name = "start_dedx",          type = "reco_particle", selector = "leading_depot_shower"},
    { name = "start_dedx",          type = "reco_particle", selector = "sub_leading_depot_shower"},
    { name = "start_straightness",  type = "reco_particle", selector = "leading_depot_shower"},
    { name = "start_straightness",  type = "reco_particle", selector = "sub_leading_depot_shower"},
    { name = "axial_spread",        type = "reco_particle", selector = "leading_depot_shower"},
    { name = "axial_spread",        type = "reco_particle", selector = "sub_leading_depot_shower"},
    { name = "directional_spread",  type = "reco_particle", selector = "leading_depot_shower"},
    { name = "directional_spread",  type = "reco_particle", selector = "sub_leading_depot_shower"},
    { name = "vertex_distance",     type = "reco_particle", selector = "leading_depot_shower"},
    { name = "vertex_distance",     type = "reco_particle", selector = "sub_leading_depot_shower"},
]

[[tree]]  #reco only single photon
name = "photon_single"
sim_only = false
mode = "reco"
cut = [
    { name = "single_shower_deposited_cut",             type = "reco",  parameters = [ "@photon_threshold"  ] } 
]
branch = [
    { name = "category",          type = "true"}
]


[[tree]]  #reco single photon + no other particles (except e)
name = "photon_nopart"
sim_only = false
mode = "reco"
cut = [
    { name = "single_shower_deposited_cut",             type = "reco",  parameters = [ "@photon_threshold"  ] },
    { name = "no_charged_pions_inclusive",              type = "reco",  parameters = [ "@pion_threshold" ]},
    { name = "no_muon_inclusive",                       type = "reco",  parameters = [ "@muon_threshold" ]}
]
branch = [

    { name = "category",          type = "true"}
]



[[tree]]  #reco single photon + no other particles (including e) + containment
name = "photon_contained"
sim_only = false
mode = "reco"
cut = [
    { name = "single_shower_deposited_cut",             type = "reco",  parameters = [ "@photon_threshold"  ] },
    { name = "no_charged_pions_inclusive",              type = "reco",  parameters = [ "@pion_threshold" ]},
    { name = "no_muon_inclusive",                       type = "reco",  parameters = [ "@muon_threshold" ]},
    { name = "contained_shower_fip_cut",                type = "reco"},
]
branch = [
    { name = "category",          type = "true"}
]



[[tree]]  #reco single shower + no other particles (including e) + containment + netrino
name = "photon_flashmatch"
sim_only = false
mode = "reco"
cut = [
    { name = "single_shower_deposited_cut",                 type = "reco",  parameters = [ "@photon_threshold"  ] },
    { name = "no_charged_pions_inclusive",                  type = "reco",  parameters = [ "@pion_threshold" ]},
    { name = "no_muon_inclusive",                           type = "reco",  parameters = [ "@muon_threshold" ]},
    { name = "contained_shower_fip_cut",                    type = "reco"},
    { name = "valid_flashmatch",                            type = "reco"}
]
branch = [
    #interaction
    { name = "photon_multiplicity_inclusive",       type = "both", parameters = [ "@photon_threshold" ]},
    { name = "photon_depot_multiplicity_inclusive", type = "true", parameters = [ "@photon_threshold" ]},
    { name = "electron_multiplicity_inclusive",     type = "both", parameters = ["@electron_threshold"]},
    { name = "pion_multiplicity_inclusive",         type = "both", parameters = [ "@pion_threshold" ]},
    { name = "proton_multiplicity_inclusive",       type = "both", parameters = [ "@proton_threshold" ]},
    { name = "muon_multiplicity_inclusive",         type = "both", parameters = ["@muon_threshold"]},
    { name = "category",                            type = "true"},
    #positioning
    { name = "vertex_x",            type = "both"},    
    { name = "vertex_y",            type = "both"},
    { name = "vertex_z",            type = "both"},
    { name = "shower_opening_angle",type = "both"},

    #leading shower
    #energy
    { name = "ke",                  type = "both_particle",     selector = "leading_depot_shower" },
    { name = "total_depositions",   type = "both_particle",     selector = "leading_depot_shower"},
    { name = "p",                   type = "both_particle",     selector = "leading_depot_shower"},
    { name = "px",                  type = "both_particle",     selector = "leading_depot_shower"},
    { name = "py",                  type = "both_particle",     selector = "leading_depot_shower"},
    { name = "pz",                  type = "both_particle",     selector = "leading_depot_shower"},
    { name = "start_dedx",          type = "reco_particle",     selector = "leading_depot_shower"},
    #positioning
    { name = "start_x",             type = "both_particle",     selector = "leading_depot_shower" },
    { name = "start_y",             type = "both_particle",     selector = "leading_depot_shower" },
    { name = "start_z",             type = "both_particle",     selector = "leading_depot_shower" },
    { name = "end_x",               type = "both_particle",     selector = "leading_depot_shower" },
    { name = "end_y",               type = "both_particle",     selector = "leading_depot_shower" },
    { name = "end_z",               type = "both_particle",     selector = "leading_depot_shower" },
    { name = "start_dir_x",         type = "both_particle",     selector = "leading_depot_shower" },
    { name = "start_dir_y",         type = "both_particle",     selector = "leading_depot_shower" },
    { name = "start_dir_z",         type = "both_particle",     selector = "leading_depot_shower" },
    #shape
    { name = "number_fragments",    type ="both_particle",      selector = "leading_depot_shower"},
    { name = "start_straightness",  type = "reco_particle",     selector = "leading_depot_shower"},
    { name = "axial_spread",        type = "reco_particle",     selector = "leading_depot_shower"},
    { name = "directional_spread",  type = "reco_particle",     selector = "leading_depot_shower"},
    { name = "vertex_distance",     type = "reco_particle",     selector = "leading_depot_shower"},
    #identifiers
    { name = "semantic_type",       type ="both_particle",      selector = "leading_depot_shower"},
    { name = "photon_softmax",      type = "reco_particle",     selector = "leading_depot_shower"},
    { name = "electron_softmax",    type = "reco_particle",     selector = "leading_depot_shower"},
    { name = "pid",                 type = "both_particle",     selector = "leading_depot_shower"},

    #subleading shower
    #energy
    { name = "ke",                  type = "both_particle",     selector = "sub_leading_depot_shower" },
    { name = "total_depositions",   type = "both_particle",     selector = "sub_leading_depot_shower"},
    { name = "p",                   type = "both_particle",     selector = "sub_leading_depot_shower"},
    { name = "px",                  type = "both_particle",     selector = "sub_leading_depot_shower"},
    { name = "py",                  type = "both_particle",     selector = "sub_leading_depot_shower"},
    { name = "pz",                  type = "both_particle",     selector = "sub_leading_depot_shower"},
    { name = "start_dedx",          type = "reco_particle",     selector = "sub_leading_depot_shower"},
    #positioning
    { name = "start_x",             type = "both_particle",     selector = "sub_leading_depot_shower" },
    { name = "start_y",             type = "both_particle",     selector = "sub_leading_depot_shower" },
    { name = "start_z",             type = "both_particle",     selector = "sub_leading_depot_shower" },
    { name = "end_x",               type = "both_particle",     selector = "sub_leading_depot_shower" },
    { name = "end_y",               type = "both_particle",     selector = "sub_leading_depot_shower" },
    { name = "end_z",               type = "both_particle",     selector = "sub_leading_depot_shower" },
    { name = "start_dir_x",         type = "both_particle",     selector = "sub_leading_depot_shower" },
    { name = "start_dir_y",         type = "both_particle",     selector = "sub_leading_depot_shower" },
    { name = "start_dir_z",         type = "both_particle",     selector = "sub_leading_depot_shower" },
    #shape
    { name = "number_fragments",    type ="both_particle",      selector = "sub_leading_depot_shower"},
    { name = "start_straightness",  type = "reco_particle",     selector = "sub_leading_depot_shower"},
    { name = "axial_spread",        type = "reco_particle",     selector = "sub_leading_depot_shower"},
    { name = "directional_spread",  type = "reco_particle",     selector = "sub_leading_depot_shower"},
    { name = "vertex_distance",     type = "reco_particle",     selector = "sub_leading_depot_shower"},
    #identifiers
    { name = "semantic_type",       type ="both_particle",      selector = "sub_leading_depot_shower"},
    { name = "photon_softmax",      type = "reco_particle",     selector = "sub_leading_depot_shower"},
    { name = "electron_softmax",    type = "reco_particle",     selector = "sub_leading_depot_shower"},
    { name = "pid",                 type = "both_particle",     selector = "sub_leading_depot_shower"},
]

[[tree]]  #reco single photon + no other particles (including e) + containment + netrino
name = "photon_one_photon"
sim_only = false
mode = "reco"
cut = [
    { name = "single_photon_deposited_cut",             type = "reco",  parameters = [ "@photon_threshold"  ] },
    { name = "no_electrons_inclusive",                  type = "reco",  parameters = [ "@electron_threshold"]},
    { name = "no_charged_pions_inclusive",              type = "reco",  parameters = [ "@pion_threshold" ]},
    { name = "no_muon_inclusive",                       type = "reco",  parameters = [ "@muon_threshold" ]},
    { name = "contained_fip_cut_depot",                 type = "reco"},
    { name = "valid_flashmatch",                        type = "reco"}
]
branch = [
    { name = "ke",                  type = "both_particle",     selector = "leading_depot_shower" },
    { name = "ke",                  type = "both_particle",     selector = "sub_leading_depot_shower" },
    { name = "total_depositions",   type = "both_particle",     selector = "leading_depot_shower"},
    { name = "total_depositions",   type = "both_particle",     selector = "sub_leading_depot_shower"},

    { name = "photon_multiplicity_inclusive",       type = "both", parameters = [ "@photon_threshold" ]},
    { name = "photon_depot_multiplicity_inclusive", type = "true", parameters = [ "@photon_threshold" ]},
    { name = "electron_multiplicity_inclusive",     type = "both", parameters = ["@electron_threshold"]},
    { name = "pion_multiplicity_inclusive",         type = "both", parameters = [ "@pion_threshold" ]},
    { name = "proton_multiplicity_inclusive",       type = "both", parameters = [ "@proton_threshold" ]},
    { name = "muon_multiplicity_inclusive",         type = "both", parameters = ["@muon_threshold"]},
    { name = "category",                            type = "true"},

    { name = "pid",                 type = "both_particle", selector="leading_depot_shower"},
    { name = "pid",                 type = "both_particle", selector="sub_leading_depot_shower"},
    { name = "shower_opening_angle",type = "both"},
    { name = "vertex_x",            type = "both"},    
    { name = "vertex_y",            type = "both"},
    { name = "vertex_z",            type = "both"},
    { name = "photon_softmax",      type = "reco_particle", selector = "leading_depot_shower"},
    { name = "photon_softmax",      type = "reco_particle", selector = "sub_leading_depot_shower"},
    { name = "electron_softmax",    type = "reco_particle", selector = "leading_depot_shower"},
    { name = "electron_softmax",    type = "reco_particle", selector = "sub_leading_depot_shower"},
    { name = "start_dedx",          type = "reco_particle", selector = "leading_depot_shower"},
    { name = "start_dedx",          type = "reco_particle", selector = "sub_leading_depot_shower"},
    { name = "start_straightness",  type = "reco_particle", selector = "leading_depot_shower"},
    { name = "start_straightness",  type = "reco_particle", selector = "sub_leading_depot_shower"},
    { name = "axial_spread",        type = "reco_particle", selector = "leading_depot_shower"},
    { name = "axial_spread",        type = "reco_particle", selector = "sub_leading_depot_shower"},
    { name = "directional_spread",  type = "reco_particle", selector = "leading_depot_shower"},
    { name = "directional_spread",  type = "reco_particle", selector = "sub_leading_depot_shower"},
    { name = "vertex_distance",     type = "reco_particle", selector = "leading_depot_shower"},
    { name = "vertex_distance",     type = "reco_particle", selector = "sub_leading_depot_shower"},
]


[[category]] #0 single photon signal with containment, no other particle
cuts = [
    { name = "single_photon_deposited_cut",             parameters = [ "@photon_threshold"  ] },
    { name = "no_electrons_inclusive",                       parameters = [ "@electron_threshold" ]},
    { name = "no_charged_pions_inclusive",                   parameters = [ "@pion_threshold" ]},
    { name = "no_muon_inclusive",                           parameters = [ "@muon_threshold" ]},
    { name = "neutrino"},
    { name = "!is_dirt" },
    { name = "contained_fip_cut_depot"}

]

[[category]] #1 single photon signal uncontained, no other particle
cuts = [
    { name = "single_photon_deposited_cut",             parameters = [ "@photon_threshold"  ] },
    { name = "no_electrons_inclusive",                       parameters = [ "@electron_threshold" ]},
    { name = "no_charged_pions_inclusive",                   parameters = [ "@pion_threshold" ]},
    { name = "no_muon_inclusive",                           parameters = [ "@muon_threshold" ]},
    { name = "neutrino"},
    { name = "!contained_fip_cut_depot"}
]

[[category]] #2 single photon signal from dirt, no other particle
cuts = [
    { name = "single_photon_deposited_cut",             parameters = [ "@photon_threshold"  ] },
    { name = "no_electrons_inclusive",                       parameters = [ "@electron_threshold" ]},
    { name = "no_charged_pions_inclusive",                   parameters = [ "@pion_threshold" ]},
    { name = "no_muon_inclusive",                           parameters = [ "@muon_threshold" ]},
    { name = "is_dirt" },
    { name = "neutrino"}
]


[[category]] #3 single photon contained + others not dirt
cuts = [
    { name = "single_photon_deposited_cut",             parameters = [ "@photon_threshold"  ] },
    { name = "neutrino"},
    { name = "!is_dirt" },
    { name = "contained_fip_cut_depot"}
]

[[category]] #4 single photon uncontained + others not dirt
cuts = [
    { name = "single_photon_deposited_cut",             parameters = [ "@photon_threshold"  ] },
    { name = "!contained_fip_cut_depot"},
    { name = "neutrino"}
]

[[category]] #5 single photon + others is dirt
cuts = [
    { name = "single_photon_deposited_cut",             parameters = [ "@photon_threshold"  ] },
    { name = "is_dirt" },
    { name = "neutrino"}
]

[[category]] #6 Neutrino contained + not dirt
cuts = [
    { name = "neutrino"},
    { name = "!is_dirt" },
    { name = "contained_fip_cut_depot"}
]

[[category]] #7 Neutrino not contained
cuts = [
    { name = "neutrino"},
    { name = "!contained_fip_cut_depot"}
]

[[category]] #8 Neutrino is dirt
cuts = [
    { name = "neutrino"},
    { name = "is_dirt" },
]


[[category]] #9 cosmic
cuts = [
    { name = "!neutrino"}
]



