[parameters]
photon_threshold = 20.0
photon_low = 10.0
electron_threshold = 10.0
electron_low = 1.0
muon_threshold = 100.0
muon_low = 1.0
pion_threshold = 130.0
pion_low = 1.0
proton_threshold = 25.0
proton_low = 1.0

[general]
#output = "/exp/sbnd/data/users/mdonnach/medulla_produce/single_photon_v2/selection/single_shower_v2_rewighted_1e20"
#output = "/pnfs/sbnd/scratch/users/mdonnach/single_shower_1e20_reweighted_output/single_shower_v2_rewighted_newdedx_nodepot"
output = "/exp/sbnd/data/users/mdonnach/medulla_produce/single_photon_v2/Merts_test"
primfn = "default_primary_classification"
pidfn = "default_pid"
fsthresh = [
    "@photon_threshold",
    "@electron_threshold",
    "@muon_threshold",
    "@pion_threshold",
    "@proton_threshold",
]

# SBND sample
[[sample]]
name = "simulation"
#path = "/pnfs/sbnd/persistent/users/mueller/MCP2025B/simulation/mc5e18/input*-reweighted.flat.caf.root"
#path = "/pnfs/sbnd/persistent/users/mueller/MCP2025B/simulation/mc5e18/input*.flat.root"
#path = "/pnfs/sbnd/persistent/users/mueller/MCP2025B/simulation/mc1e20/input*.flat.caf.root"
path = "/pnfs/sbnd/persistent/users/mueller/MCP2025B/simulation/mc1e20/input264-reweighted.flat.caf.root"
#path = "/pnfs/sbnd/persistent/users/mueller/MCP2025B/simulation/mc1e20/input[4-7][0-9][0-9]-reweighted.flat.caf.root"
#path = "/pnfs/sbnd/persistent/users/mueller/MCP2025B/simulation/mc1e20/input387-reweighted.flat.caf.root"
#path = "root://fndca1.fnal.gov:1094//pnfs/sbnd/persistent/users/mueller/MCP2025B/simulation/mc1e20/input*-reweighted.flat.caf.root"
#path = "/pnfs/sbnd/scratch/users/mueller/MCP2025B/gen1_updated_training/03162026/input*.flat.root"
ismc = true
disable = false # Optional: default = falses


[[tree]]  #True single photon selection
name = "true_radiative_delta"
sim_only = true
mode = "true"
cut = [
    { name = "!iscc",                           type = "mctruth" },
    { name = "no_neutral_pions",                type = "mctruth"},
    { name = "!is_dirt",                        type = "true"}


]
branch = [
    #mctruth
    { name = "iscc",                                    type = "mctruth" },
    { name = "interaction_mode",                        type = "mctruth" },
    { name = "interaction_type",                        type = "mctruth" },
    { name = "nphotons_srtruth",                        type = "mctruth"},
    #{ name = "npi0s_srtruth",                           type = "mctruth"},
]


