[parameters]
photon_threshold = 20.0
photon_low = 2.0
electron_threshold = 10.0
electron_low = 10.0
muon_threshold = 100.0
muon_low = 25.0
pion_threshold = 130.0
pion_low = 25.0
proton_threshold = 25.0
proton_low = 25.0

[general]
output = "/exp/sbnd/data/users/mdonnach/medulla_produce/single_photon_v2/selection/true_test"
primfn = "default_primary_classification"
pidfn = "default_pid"
fsthresh = [
    "@photon_threshold",
    "@electron_threshold",
    "@muon_threshold",
    "@pion_threshold",
    "@proton_threshold",
]

# SBND sample
[[sample]]
name = "simulation"
#path = "/pnfs/sbnd/persistent/users/mueller/MCP2025B/simulation/mc5e18/input*-reweighted.flat.caf.root"
path = "/pnfs/sbnd/persistent/users/mueller/MCP2025B/simulation/mc5e18/input*.flat.root"
#path = "/pnfs/sbnd/scratch/users/mueller/MCP2025B/gen1_updated_training/03162026/input*.flat.root"
ismc = true
disable = false # Optional: default = falses


[[tree]]  #True single photon selection
name = "photon_true_neutrino"
sim_only = false
mode = "true"
cut = [
    { name = "single_photon_deposited_cut",             type = "true",  parameters = [ "@photon_threshold"  ] },
    { name = "no_electrons_inclusive",                       type = "true",  parameters = [ "@electron_threshold" ]},
    { name = "no_charged_pions_inclusive",                   type = "true",  parameters = [ "@pion_threshold" ]},
    { name = "no_muon_inclusive",                           type = "true",  parameters = [ "@muon_threshold" ]},
    { name = "contained_fip_cut_depot",                    type = "true"},
    { name = "neutrino",                  type = "true"}
]
branch = [
    { name = "ke",                type = "both_particle", selector = "leading_photon" },
    { name = "ke",                type = "both_particle", selector = "sub_leading_photon" },
    { name = "photon_opening_angle",   type = "both"},
    { name = "photon_multiplicity_inclusive", type = "both", parameters = [ "@photon_low" ]},
    { name = "photon_multiplicity", type = "both", parameters = [ "@photon_low" ]},
    { name = "photon_depot_multiplicity_inclusive", type = "both", parameters = [ "@photon_low" ]},
    { name = "electron_multiplicity_inclusive", type = "both", parameters = ["@electron_threshold"]},
    { name = "pion_multiplicity_inclusive", type = "both", parameters = [ "@pion_threshold" ]},
    { name = "proton_multiplicity_inclusive", type = "both", parameters = [ "@proton_threshold" ]},
    { name = "muon_multiplicity_inclusive", type = "both", parameters = ["@muon_threshold"]},
    { name = "total_depositions",  type = "both_particle",  selector = "leading_photon"},
    { name = "total_depositions",  type = "both_particle",  selector = "sub_leading_photon"},
    { name = "is_dirt", type = "true"}
]

