[parameters]
photon_threshold = 20.0
photon_low = 10.0
electron_threshold = 10.0
electron_low = 10.0
muon_threshold = 100.0
muon_low = 25.0
pion_threshold = 130.0
pion_low = 25.0
proton_threshold = 25.0
proton_low = 25.0

[general]
output = "/exp/sbnd/data/users/mdonnach/medulla_produce/single_photon_v2/selection/single_photon_v1"
primfn = "default_primary_classification"
pidfn = "default_pid"
fsthresh = [
    "@photon_threshold",
    "@electron_threshold",
    "@muon_threshold",
    "@pion_threshold",
    "@proton_threshold",
]

# SBND sample
[[sample]]
name = "simulation"
#path = "/pnfs/sbnd/persistent/users/mueller/MCP2025B/simulation/mc5e18/input*-reweighted.flat.caf.root"
path = "/pnfs/sbnd/persistent/users/mueller/MCP2025B/simulation/mc5e18/input*.flat.root"
#path = "/pnfs/sbnd/scratch/users/mueller/MCP2025B/gen1_updated_training/03162026/input*.flat.root"
ismc = true
disable = false # Optional: default = falses


[[tree]]  #True single photon selection
name = "photon_true_neutrino"
sim_only = false
mode = "true"
cut = [
    { name = "single_photon_deposited_cut",             type = "true",  parameters = [ "@photon_threshold"  ] },
    { name = "no_electrons_inclusive",                       type = "true",  parameters = [ "@electron_threshold" ]},
    { name = "no_charged_pions_inclusive",                   type = "true",  parameters = [ "@pion_threshold" ]},
    { name = "no_muon_inclusive",                           type = "true",  parameters = [ "@muon_threshold" ]},
    { name = "contained_fip_cat_depot",                    type = "true"},
    { name = "neutrino",                  type = "true"}
]
branch = [
    { name = "ke",                type = "both_particle", selector = "leading_photon" },
    { name = "ke",                type = "both_particle", selector = "sub_leading_photon" },
    { name = "photon_opening_angle",   type = "both"},
    { name = "photon_multiplicity_inclusive", type = "both", parameters = [ "@photon_threshold" ]},
    { name = "photon_depot_multiplicity_inclusive", type = "true", parameters = [ "@photon_threshold" ]},
    { name = "electron_multiplicity_inclusive", type = "both", parameters = ["@electron_threshold"]},
    { name = "pion_multiplicity_inclusive", type = "both", parameters = [ "@pion_threshold" ]},
    { name = "proton_multiplicity_inclusive", type = "both", parameters = [ "@proton_threshold" ]},
    { name = "muon_multiplicity_inclusive", type = "both", parameters = ["@muon_threshold"]},
    { name = "category",          type = "true"},
    { name = "total_depositions",  type = "both_particle",  selector = "leading_photon"},
    { name = "total_depositions",  type = "both_particle",  selector = "sub_leading_photon"},
    
    {name = "vertex_x",           type = "both"},    
    {name = "vertex_y",           type = "both"},
    {name = "vertex_z",           type = "both"},
    {name = "photon_softmax",       type = "reco_particle", selector = "leading_photon"},
    {name = "photon_softmax",       type = "reco_particle", selector = "sub_leading_photon"},
    {name = "two_photon_seperation",     type = "both"},
    {name = "start_dedx",           type = "reco_particle", selector = "leading_photon"},
]

[[tree]]  #reco only single photon
name = "photon_single"
sim_only = false
mode = "reco"
cut = [
    { name = "single_photon_observed_cut",             type = "reco",  parameters = [ "@photon_threshold"  ] } 
]
branch = [
    { name = "ke",                type = "both_particle", selector = "leading_photon" },
    { name = "ke",                type = "both_particle", selector = "sub_leading_photon" },
    { name = "photon_opening_angle",   type = "both"},
    { name = "photon_multiplicity_inclusive", type = "both", parameters = [ "@photon_threshold" ]},
    { name = "photon_depot_multiplicity_inclusive", type = "true", parameters = [ "@photon_threshold" ]},
    { name = "electron_multiplicity_inclusive", type = "both", parameters = ["@electron_threshold"]},
    { name = "pion_multiplicity_inclusive", type = "both", parameters = [ "@pion_threshold" ]},
    { name = "proton_multiplicity_inclusive", type = "both", parameters = [ "@proton_threshold" ]},
    { name = "muon_multiplicity_inclusive", type = "both", parameters = ["@muon_threshold"]},
    { name = "category",          type = "true"}
]


[[tree]]  #reco single photon + no other particles (except e)
name = "photon_nopart"
sim_only = false
mode = "reco"
cut = [
    { name = "single_photon_observed_cut",             type = "reco",  parameters = [ "@photon_threshold"  ] },
    { name = "no_charged_pions_inclusive",                   type = "reco",  parameters = [ "@pion_threshold" ]},
    { name = "no_muon_inclusive",                           type = "reco",  parameters = [ "@muon_threshold" ]}
]
branch = [
    { name = "ke",                type = "both_particle", selector = "leading_photon" },
    { name = "ke",                type = "both_particle", selector = "sub_leading_photon" },
    { name = "photon_opening_angle",   type = "both"},
    { name = "photon_multiplicity_inclusive", type = "both", parameters = [ "@photon_threshold" ]},
    { name = "photon_depot_multiplicity_inclusive", type = "true", parameters = [ "@photon_threshold" ]},
    { name = "electron_multiplicity_inclusive", type = "both", parameters = ["@electron_threshold"]},
    { name = "pion_multiplicity_inclusive", type = "both", parameters = [ "@pion_threshold" ]},
    { name = "proton_multiplicity_inclusive", type = "both", parameters = [ "@proton_threshold" ]},
    { name = "muon_multiplicity_inclusive", type = "both", parameters = ["@muon_threshold"]},
    { name = "category",          type = "true"}
]

[[tree]]  #reco single photon + no other particles (including e)
name = "photon_noe"
sim_only = false
mode = "reco"
cut = [
    { name = "single_photon_observed_cut",             type = "reco",  parameters = [ "@photon_threshold"  ] },
    { name = "no_electrons_inclusive",                       type = "reco",  parameters = [ "@electron_threshold" ]},
    { name = "no_charged_pions_inclusive",                   type = "reco",  parameters = [ "@pion_threshold" ]},
    { name = "no_muon_inclusive",                           type = "reco",  parameters = [ "@muon_threshold" ]}
]
branch = [
    { name = "ke",                type = "both_particle", selector = "leading_photon" },
    { name = "ke",                type = "both_particle", selector = "sub_leading_photon" },
    { name = "photon_opening_angle",   type = "both"},
    { name = "photon_multiplicity_inclusive", type = "both", parameters = [ "@photon_threshold" ]},
    { name = "photon_depot_multiplicity_inclusive", type = "true", parameters = [ "@photon_threshold" ]},
    { name = "electron_multiplicity_inclusive", type = "both", parameters = ["@electron_threshold"]},
    { name = "pion_multiplicity_inclusive", type = "both", parameters = [ "@pion_threshold" ]},
    { name = "proton_multiplicity_inclusive", type = "both", parameters = [ "@proton_threshold" ]},
    { name = "muon_multiplicity_inclusive", type = "both", parameters = ["@muon_threshold"]},
    { name = "category",          type = "true"}
]

[[tree]]  #reco single photon + no other particles (including e) + containment
name = "photon_contained"
sim_only = false
mode = "reco"
cut = [
    { name = "single_photon_observed_cut",             type = "reco",  parameters = [ "@photon_threshold"  ] },
    { name = "no_electrons_inclusive",                       type = "reco",  parameters = [ "@electron_threshold" ]},
    { name = "no_charged_pions_inclusive",                   type = "reco",  parameters = [ "@pion_threshold" ]},
    { name = "no_muon_inclusive",                           type = "reco",  parameters = [ "@muon_threshold" ]},
    { name = "contained_fip_cat",                    type = "reco"},
]
branch = [
    { name = "ke",                type = "both_particle", selector = "leading_photon" },
    { name = "ke",                type = "both_particle", selector = "sub_leading_photon" },
    { name = "photon_opening_angle",   type = "both"},
    { name = "photon_multiplicity_inclusive", type = "both", parameters = [ "@photon_threshold" ]},
    { name = "photon_depot_multiplicity_inclusive", type = "true", parameters = [ "@photon_threshold" ]},
    { name = "electron_multiplicity_inclusive", type = "both", parameters = ["@electron_threshold"]},
    { name = "pion_multiplicity_inclusive", type = "both", parameters = [ "@pion_threshold" ]},
    { name = "proton_multiplicity_inclusive", type = "both", parameters = [ "@proton_threshold" ]},
    { name = "muon_multiplicity_inclusive", type = "both", parameters = ["@muon_threshold"]},
    { name = "category",          type = "true"}
]



[[tree]]  #reco single photon + no other particles (including e) + containment + netrino
name = "photon_flashmatch"
sim_only = false
mode = "reco"
cut = [
    { name = "single_photon_observed_cut",             type = "reco",  parameters = [ "@photon_threshold"  ] },
    { name = "no_electrons_inclusive",                       type = "reco",  parameters = [ "@electron_threshold" ]},
    { name = "no_charged_pions_inclusive",                   type = "reco",  parameters = [ "@pion_threshold" ]},
    { name = "no_muon_inclusive",                           type = "reco",  parameters = [ "@muon_threshold" ]},
    { name = "contained_fip_cat",                    type = "reco"},
    { name = "valid_flashmatch",                  type = "reco"}
]
branch = [
    { name = "ke",                type = "both_particle", selector = "leading_photon" },
    { name = "ke",                type = "both_particle", selector = "sub_leading_photon" },

    { name = "photon_opening_angle",   type = "both"},
    { name = "photon_multiplicity_inclusive", type = "both", parameters = [ "@photon_threshold" ]},
    { name = "photon_depot_multiplicity_inclusive", type = "true", parameters = [ "@photon_threshold" ]},
    { name = "electron_multiplicity_inclusive", type = "both", parameters = ["@electron_threshold"]},
    { name = "pion_multiplicity_inclusive", type = "both", parameters = [ "@pion_threshold" ]},
    { name = "proton_multiplicity_inclusive", type = "both", parameters = [ "@proton_threshold" ]},
    { name = "muon_multiplicity_inclusive", type = "both", parameters = ["@muon_threshold"]},
    { name = "category",          type = "true"},
    { name = "total_depositions",  type = "both_particle",  selector = "leading_photon"},
    { name = "total_depositions",  type = "both_particle",  selector = "sub_leading_photon"},

    {name = "vertex_x",           type = "both"},    
    {name = "vertex_y",           type = "both"},
    {name = "vertex_z",           type = "both"},
    {name = "photon_softmax",       type = "reco_particle", selector = "leading_photon"},
    {name = "photon_softmax",       type = "reco_particle", selector = "sub_leading_photon"},
    {name = "start_dedx",           type = "reco_particle", selector = "leading_photon"},
    {name = "two_photon_seperation",     type = "both"}
]



[[category]] #0 single photon signal with containment, no other particle
cuts = [
    { name = "single_photon_deposited_cut",             parameters = [ "@photon_threshold"  ] },
    { name = "no_electrons_inclusive",                       parameters = [ "@electron_threshold" ]},
    { name = "no_charged_pions_inclusive",                   parameters = [ "@pion_threshold" ]},
    { name = "no_muon_inclusive",                           parameters = [ "@muon_threshold" ]},
    { name = "neutrino"},
    { name = "!is_dirt" },
    { name = "contained_fip_cat_depot"}

]

[[category]] #1 single photon signal uncontained, no other particle
cuts = [
    { name = "single_photon_deposited_cut",             parameters = [ "@photon_threshold"  ] },
    { name = "no_electrons_inclusive",                       parameters = [ "@electron_threshold" ]},
    { name = "no_charged_pions_inclusive",                   parameters = [ "@pion_threshold" ]},
    { name = "no_muon_inclusive",                           parameters = [ "@muon_threshold" ]},
    { name = "neutrino"},
    { name = "!contained_fip_cat_depot"}
]

[[category]] #2 single photon signal from dirt, no other particle
cuts = [
    { name = "single_photon_deposited_cut",             parameters = [ "@photon_threshold"  ] },
    { name = "no_electrons_inclusive",                       parameters = [ "@electron_threshold" ]},
    { name = "no_charged_pions_inclusive",                   parameters = [ "@pion_threshold" ]},
    { name = "no_muon_inclusive",                           parameters = [ "@muon_threshold" ]},
    { name = "is_dirt" },
    { name = "neutrino"}
]


[[category]] #3 single photon contained + others not dirt
cuts = [
    { name = "single_photon_deposited_cut",             parameters = [ "@photon_threshold"  ] },
    { name = "neutrino"},
    { name = "!is_dirt" },
    { name = "contained_fip_cat_depot"}
]

[[category]] #4 single photon uncontained + others not dirt
cuts = [
    { name = "single_photon_deposited_cut",             parameters = [ "@photon_threshold"  ] },
    { name = "!contained_fip_cat_depot"},
    { name = "neutrino"}
]

[[category]] #5 single photon + others is dirt
cuts = [
    { name = "single_photon_deposited_cut",             parameters = [ "@photon_threshold"  ] },
    { name = "is_dirt" },
    { name = "neutrino"}
]

[[category]] #6 Neutrino contained + not dirt
cuts = [
    { name = "neutrino"},
    { name = "!is_dirt" },
    { name = "contained_fip_cat_depot"}
]

[[category]] #7 Neutrino not contained
cuts = [
    { name = "neutrino"},
    { name = "!contained_fip_cat_depot"}
]

[[category]] #8 Neutrino is dirt
cuts = [
    { name = "neutrino"},
    { name = "is_dirt" },
]


[[category]] #9 cosmic
cuts = [
    { name = "!neutrino"}
]



